name: test-and-build
on: [push, pull_request]
jobs:
  build:
    name: test & build - node.js
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        # Support LTS versions based on https://nodejs.org/en/about/releases/
        node-version: ['20']
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: static checks
        run: npm run lint
      - name: Run automated tests
        run: npm test
      - name: Run vite & rollup
        run: npm run build
